name: Benchmark

on:
  push:

jobs:
  benchmark:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    name: Benchmark (${{ matrix.language }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: python
            install: pip install psutil
            run_dir: benchmarks/python
            run_cmd: python3 main.py
            setup: python
            version: "3.11"
            artifact: benchmark-python

          - language: javascript
            install: ""
            run_dir: benchmarks/javascript
            run_cmd: node main.js
            setup: node
            version: "20"
            artifact: benchmark-javascript

    steps:
      - uses: actions/checkout@v4

      - name: python setup
        if: matrix.setup == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: node setup
        if: matrix.setup == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: install
        if: matrix.install != ''
        run: ${{ matrix.install }}

      - name: run benchmark
        run: |
          cd ${{ matrix.run_dir }}
          ${{ matrix.run_cmd }} > result.json

      - name: build result
        run: |
          mkdir -p results
          jq -n --slurpfile data ${{ matrix.run_dir }}/result.json \
            --arg lang "${{ matrix.language }}" \
            '{language:$lang, benchmarks:$data[0].benchmarks}' > results/result.json

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: results/result.json

  aggregate:
    needs: benchmark
    runs-on: ubuntu-latest
    name: Aggregate results

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: merge results
        run: |
          find artifacts -type f -name "result.json"

          jq -s '
            map({
              language: .language,
              benchmarks: .benchmarks
            })
          ' artifacts/*/result.json > results.json

      - name: show final json
        run: cat results.json

      - name: upload merged result
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-global
          path: results.json
